### ISSUE TITLE
[docs] openssl 3.2 is with QUIC protocol

### ISSUE THREAD

**Issue by talregev** [ngtcp2/ngtcp2#997] opened 2023-10-30 00:47 UTC
openssl 3.2 is with QUIC protocol
It should add to document: 

https://github.com/ngtcp2/ngtcp2/blob/main/README.rst?plain=1#L58

**Comment by tatsuhiro-t** [comment] 2023-10-30 07:02
Duplicate of #990

**Closed by tatsuhiro-t** 2023-10-30 07:02 UTC
